# Generated by Django 4.2 on 2023-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dia', models.IntegerField(verbose_name='Dia')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em:')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ('mes', '-dia'),
            },
        ),
    ]
